Loading page
JiangTianXiang/instagram-clone pull request #8
Opened 2021-06-23 18:16 UTC by JiangTianXiang

-Added loading screen component 
-Implemented loading screen for all pages
-Resolved incorrect prompt message for collection page, when all photos are loaded

2021-06-23 23:59 UTC, yoloOnTheBattlefield requested changes

2021-06-23 23:59 UTC, yoloOnTheBattlefield commented on src/pages/Explore/index.js
> +    }
`const hasData = this.state.data.length`

2021-06-23 23:59 UTC, yoloOnTheBattlefield commented on src/pages/Explore/index.js
>        this.setState({ hasError: false });
don't forget to add the loading propery

2021-06-23 23:59 UTC, yoloOnTheBattlefield commented on src/pages/User/index.js
> +                  <DetailDiv>{`${this.state.user.total_collections} collections`}</DetailDiv>
maybe it's better to destructure the user
`const {user} = this.state`
then destructre the values
`const { total_likes, total_photos, total_collections, username, profile_image } = user`

2021-06-24 02:33 UTC, JiangTianXiang commented on src/pages/Explore/index.js
>        this.setState({ hasError: false });
Are you talking about Loading in the state? I removed it initially since it always triggers a page reset when infinite scrolls load in more data

2021-06-24 12:17 UTC, yoloOnTheBattlefield commented on src/pages/Explore/index.js
>        this.setState({ hasError: false });
that was because of the implementation, setting error to false doesn't trigger a page reset, the flag should be there regardless

2021-06-24 12:19 UTC, yoloOnTheBattlefield commented on src/pages/FavoriteImage/index.js
>      const noImage = this.state.data.length === 0;
what's the difference between has data and no image?

2021-06-24 16:57 UTC, yoloOnTheBattlefield approved these changes

2021-06-24 17:29 UTC, merged